import { IPlayer } from './app/interfaces/IPlayer';

export const PLAYERS: IPlayer[] = [
  {
    id: 1,
    name: 'Tabbie Asals',
    shirtNumber: 58,
    team: 'Dicrostonyx groenlandicus',
    age: 32,
    wage: 2541,
    endOfContract: new Date('2022-01-10'),
  },
  {
    id: 2,
    name: 'Jory Giuron',
    shirtNumber: 4,
    team: 'Dicrostonyx groenlandicus',
    age: 22,
    wage: 2291,
    endOfContract: new Date('2022-05-15'),
  },
  {
    id: 3,
    name: 'Nita Bendle',
    shirtNumber: 100,
    team: 'Dicrostonyx groenlandicus',
    age: 25,
    wage: 2652,
    endOfContract: new Date('2021-09-19'),
  },
  {
    id: 4,
    name: 'Erhart Agar',
    shirtNumber: 2,
    team: 'Dicrostonyx groenlandicus',
    age: 20,
    wage: 2454,
    endOfContract: new Date('2022-01-06'),
  },
  {
    id: 5,
    name: 'Loree Ferguson',
    shirtNumber: 25,
    team: 'Dicrostonyx groenlandicus',
    age: 28,
    wage: 2657,
    endOfContract: new Date('2021-10-13'),
  },
  {
    id: 6,
    name: 'Nissie Tilling',
    shirtNumber: 8,
    team: 'Dicrostonyx groenlandicus',
    age: 29,
    wage: 1970,
    endOfContract: new Date('2022-08-21'),
  },
  {
    id: 7,
    name: 'Andros Di Batista',
    shirtNumber: 69,
    team: 'Dicrostonyx groenlandicus',
    age: 19,
    wage: 1458,
    endOfContract: new Date('2022-08-29'),
  },
  {
    id: 8,
    name: 'Jemmy Damato',
    shirtNumber: 85,
    team: 'Dicrostonyx groenlandicus',
    age: 19,
    wage: 3188,
    endOfContract: new Date('2022-07-18'),
  },
  {
    id: 9,
    name: 'Daisy Ellick',
    shirtNumber: 6,
    team: 'Dicrostonyx groenlandicus',
    age: 18,
    wage: 2137,
    endOfContract: new Date('2022-05-19'),
  },
  {
    id: 10,
    name: 'Peyter Caush',
    shirtNumber: 26,
    team: 'Dicrostonyx groenlandicus',
    age: 35,
    wage: 1044,
    endOfContract: new Date('2022-06-25'),
  },
  {
    id: 11,
    name: 'Edna Plowman',
    shirtNumber: 75,
    team: 'Conolophus subcristatus',
    age: 35,
    wage: 2433,
    endOfContract: new Date('2022-08-06'),
  },
  {
    id: 12,
    name: 'Britt Stockle',
    shirtNumber: 45,
    team: 'Conolophus subcristatus',
    age: 22,
    wage: 1360,
    endOfContract: new Date('2022-01-18'),
  },
  {
    id: 13,
    name: 'Jordan Daventry',
    shirtNumber: 85,
    team: 'Conolophus subcristatus',
    age: 24,
    wage: 3141,
    endOfContract: new Date('2022-05-07'),
  },
  {
    id: 14,
    name: 'Ralina Eiler',
    shirtNumber: 61,
    team: 'Conolophus subcristatus',
    age: 33,
    wage: 1334,
    endOfContract: new Date('2022-05-04'),
  },
  {
    id: 15,
    name: 'Dorie Halm',
    shirtNumber: 63,
    team: 'Conolophus subcristatus',
    age: 25,
    wage: 2963,
    endOfContract: new Date('2022-01-12'),
  },
  {
    id: 16,
    name: "Brooks O'Lynn",
    shirtNumber: 6,
    team: 'Conolophus subcristatus',
    age: 35,
    wage: 1166,
    endOfContract: new Date('2022-02-20'),
  },
  {
    id: 17,
    name: 'Cole Joist',
    shirtNumber: 78,
    team: 'Conolophus subcristatus',
    age: 26,
    wage: 2385,
    endOfContract: new Date('2021-11-05'),
  },
  {
    id: 18,
    name: 'Nathalia Castillo',
    shirtNumber: 34,
    team: 'Conolophus subcristatus',
    age: 20,
    wage: 1237,
    endOfContract: new Date('2022-07-13'),
  },
  {
    id: 19,
    name: 'Auroora Dunbabin',
    shirtNumber: 56,
    team: 'Conolophus subcristatus',
    age: 20,
    wage: 1055,
    endOfContract: new Date('2021-10-01'),
  },
  {
    id: 20,
    name: 'Jermain Kochel',
    shirtNumber: 20,
    team: 'Conolophus subcristatus',
    age: 25,
    wage: 2990,
    endOfContract: new Date('2021-09-10'),
  },
  {
    id: 21,
    name: 'Josefa Bonnette',
    shirtNumber: 66,
    team: 'Corvus albicollis',
    age: 21,
    wage: 1708,
    endOfContract: new Date('2022-07-20'),
  },
  {
    id: 22,
    name: 'Jacob Birdwistle',
    shirtNumber: 99,
    team: 'Corvus albicollis',
    age: 26,
    wage: 2993,
    endOfContract: new Date('2022-06-25'),
  },
  {
    id: 23,
    name: 'Benjie Cardinal',
    shirtNumber: 100,
    team: 'Corvus albicollis',
    age: 28,
    wage: 3027,
    endOfContract: new Date('2022-04-20'),
  },
  {
    id: 24,
    name: 'Galvan Copelli',
    shirtNumber: 13,
    team: 'Corvus albicollis',
    age: 25,
    wage: 3058,
    endOfContract: new Date('2021-09-29'),
  },
  {
    id: 25,
    name: 'Corrinne Tydd',
    shirtNumber: 2,
    team: 'Corvus albicollis',
    age: 19,
    wage: 1069,
    endOfContract: new Date('2022-08-17'),
  },
  {
    id: 26,
    name: 'Hannie Faichney',
    shirtNumber: 15,
    team: 'Corvus albicollis',
    age: 31,
    wage: 1274,
    endOfContract: new Date('2021-10-05'),
  },
  {
    id: 27,
    name: 'Goldy Readings',
    shirtNumber: 74,
    team: 'Corvus albicollis',
    age: 19,
    wage: 2830,
    endOfContract: new Date('2021-10-22'),
  },
  {
    id: 28,
    name: 'Tiffie Macknish',
    shirtNumber: 83,
    team: 'Corvus albicollis',
    age: 25,
    wage: 2919,
    endOfContract: new Date('2022-06-27'),
  },
  {
    id: 29,
    name: 'Melodie Kearsley',
    shirtNumber: 73,
    team: 'Corvus albicollis',
    age: 30,
    wage: 1972,
    endOfContract: new Date('2022-08-13'),
  },
  {
    id: 30,
    name: 'Tabbie Kunz',
    shirtNumber: 53,
    team: 'Corvus albicollis',
    age: 29,
    wage: 2811,
    endOfContract: new Date('2021-12-13'),
  },
];
